version: "3"
services:
  web:
    build: .
    ports:
    - "65432:65432"
    networks:
      - webnet
  swagger:
    image: "swaggerapi/swagger-ui"
    ports:
    - "80:8080"
    environment:
      API_URL: http://ec2-13-231-105-253.ap-northeast-1.compute.amazonaws.com:65432/api/swagger.json
    networks:
      - webnet
networks:
  webnet:
  