version: "3"
services:
  web:
    build: . 
    ports:
    - "65432:65432"
    networks:
      - webnet
  swagger:
    image: "swaggerapi/swagger-ui"
    ports:
    - "80:8080"
    environment:
      API_URL: http://localhost:65432/api/swagger.json
    networks:
      - webnet
networks:
  webnet:
  